apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
        - name: init-script
          configMap:
            name: {{ .Release.Name }}-init-script
            defaultMode: 0755
      securityContext:
        fsGroup: 200
      containers:
        - name: pdns
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #command: ["sleep", "infinity"]  
          ports:
            {{- if .Values.service.webserver.enabled }}
            - containerPort: {{ .Values.service.webserver.port }}
            {{- end }}
            {{- if .Values.service.dnstcp.enabled }}
            - containerPort: {{ .Values.service.dnstcp.port  }}
              protocol: {{ .Values.service.dnstcp.protocol }}
            {{- end }}
            {{- if .Values.service.dnsudp.enabled }}
            - containerPort: {{ .Values.service.dnsudp.port }}
              protocol: {{ .Values.service.dnsudp.protocol }}
            {{- end }}
          env:
            {{- range .Values.pdns.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.pdns.resources | nindent 12 }}
          volumeMounts:
            #- name: pdns-data
            #  mountPath: /pdns-data
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.service.webserver.port }}
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.service.webserver.port }}
          #   initialDelaySeconds: 60
          #   periodSeconds: 30
